# ---------------------------------------------------------------
# python best courses https://courses.tanpham.org/
# ---------------------------------------------------------------

# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [9]:
import numpy as np
print(np.__version__)
np.show_config()

1.16.5
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/User/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', '

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
import numpy as np
a = np.zeros(10)
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [8]:
import numpy as np
a = np.zeros((10,10))
print("%d bytes" %(a.size*a.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
%run `python -c "import numpy; numpy.info(numpy.add)"

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [11]:
import numpy as np
a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [12]:
import numpy as np
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [13]:
import numpy as np
a = np.arange(10)
print(a[::-1])

[9 8 7 6 5 4 3 2 1 0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [14]:
import numpy as np
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [15]:
import numpy as npp
a = [1,2,0,0,4,0]
az = np.nonzero(a)
print(az)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [18]:
import numpy as np
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [22]:
import numpy as np
a = np.random.random((3,3,3))
print(a)

[[[0.74719513 0.05065501 0.31494861]
  [0.02557249 0.78403622 0.51726916]
  [0.79453656 0.96366736 0.35456846]]

 [[0.59907115 0.66601172 0.45518515]
  [0.855423   0.62056533 0.72020681]
  [0.39936784 0.39144414 0.25320431]]

 [[0.53185095 0.78940264 0.55109006]
  [0.34116332 0.08795809 0.90730426]
  [0.37914311 0.20941419 0.29846289]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [29]:
import numpy as np
a = np.random.random((10,10))
print(a,'\n')
print(a.max())
print(a.min())

[[0.03855889 0.43079762 0.49147313 0.44067586 0.11561312 0.44997742
  0.96139024 0.57395963 0.95865427 0.01627495]
 [0.29403835 0.22867305 0.20940811 0.7409597  0.43480619 0.94098379
  0.53197442 0.5505651  0.80408498 0.51024546]
 [0.53280829 0.19212923 0.27506806 0.06845607 0.03550143 0.26734994
  0.84279692 0.49692036 0.78540936 0.45651081]
 [0.69270562 0.60743155 0.16135427 0.72183687 0.03703314 0.82511513
  0.3982285  0.1972315  0.42858828 0.97415599]
 [0.05194891 0.59240809 0.93667408 0.15768704 0.30661575 0.54868627
  0.28757091 0.27536469 0.61885647 0.62754751]
 [0.59475452 0.49444336 0.61091041 0.06492369 0.70900037 0.3509936
  0.84704661 0.19503214 0.61052454 0.23606844]
 [0.86409041 0.4797602  0.90723877 0.11929925 0.4776951  0.04507564
  0.08067509 0.6067906  0.15681798 0.41471552]
 [0.89783582 0.07655557 0.91224675 0.13920896 0.50431452 0.5977155
  0.58309771 0.80958718 0.0917899  0.14886253]
 [0.70452909 0.37654804 0.44797604 0.06972468 0.52636932 0.23315484
  0.82904148 0

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [28]:
import numpy as np
a = np.random.random(30)
print(a)
m = a.mean()
print('\n',m)

[0.39490469 0.44801872 0.22797279 0.80033568 0.78618191 0.37634471
 0.04043115 0.94444045 0.69324594 0.38617598 0.48932825 0.7276133
 0.0597616  0.33801384 0.24082504 0.13018426 0.41323738 0.14442753
 0.5938894  0.5474029  0.21124047 0.63983329 0.6972892  0.88023438
 0.49611449 0.66000798 0.52832831 0.3894435  0.94349328 0.15994118]

 0.47962205338541236


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [35]:
import numpy as np
a = np.ones((10,10))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [37]:
import numpy as np
a = np.ones((5,5))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [38]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3*0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [41]:
import numpy as np
a = np.diag(1 + np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [43]:
import numpy as np
a = np.zeros((8,8))
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [44]:
import numpy as np
a = np.unravel_index(100,(6,7,8))
print(a)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [45]:
import numpy as np
a = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [47]:
import numpy as np
a = np.random.random((5,5))
print(a,'\n')
a = (a - a.min())/(a.max()-a.min())
print(a)

[[0.55620578 0.425956   0.51965805 0.84319525 0.16131173]
 [0.01963733 0.34353726 0.62805403 0.74365996 0.6235098 ]
 [0.20384178 0.02893686 0.5297148  0.06932692 0.05166117]
 [0.72720815 0.4791639  0.19990407 0.72101712 0.32058054]
 [0.98612167 0.18939985 0.37425549 0.2294526  0.69198401]] 

[[0.55517553 0.42040895 0.51736039 0.85211719 0.14658738]
 [0.         0.33513211 0.62951532 0.74913022 0.62481351]
 [0.19059228 0.00962203 0.5277659  0.05141272 0.03313436]
 [0.7321079  0.47546199 0.18651801 0.72570218 0.31137929]
 [1.         0.17564953 0.36691558 0.21709123 0.69566226]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [50]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [53]:
import numpy as np
a = np.random.random((5,3))
b = np.random.random((3,2))
c = np.dot(a,b)
print(a,'\n\n',b,'\n\n',c)

[[0.03285707 0.31967886 0.13876215]
 [0.20834353 0.23518394 0.68512285]
 [0.3198118  0.29329085 0.61720687]
 [0.98204646 0.75092665 0.22962406]
 [0.06118465 0.11968101 0.52641452]] 

 [[0.87319695 0.96808714]
 [0.52426585 0.31048565]
 [0.5818238  0.35709365]] 

 [[0.27702252 0.18061529]
 [0.70384463 0.51936896]
 [0.79212671 0.62106895]
 [1.38480591 1.26585579]
 [0.42245141 0.28437059]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [58]:
import numpy as np
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [59]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [62]:
import numpy as np
Z = np.ones((4,4))
print(Z**Z)
# print(2 << Z >> 2) 
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
# print(Z<Z>Z)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[False False False False]
 [False False False False]
 [False False False False]
 [False False False False]]
[[0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j]
 [0.+1.j 0.+1.j 0.+1.j 0.+1.j]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [63]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
C:\Users\User\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 29. How to round away from zero a float array ? (★☆☆)

In [65]:
import numpy as np
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[ 7.43653996  0.82708263 -8.37789324 -9.08472059 -5.60154701 -0.19021685
 -2.74947867  4.6835831  -6.35101443  8.99222817]
[  8.   1.  -9. -10.  -6.  -1.  -3.   5.  -7.   9.]


#### 30. How to find common values between two arrays? (★☆☆)

In [67]:
import numpy as np
a = np.random.randint(0,10,10)
b = np.random.randint(0,10,10)
print(a,'\n',b,'\n')
print(np.intersect1d(a,b))

[9 0 5 0 4 9 0 2 2 3] 
 [1 5 3 6 3 7 1 6 2 2] 

[2 3 5]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [68]:
import numpy as np

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-68-c9bf38000366>, line 10)

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [69]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday)
print(today)
print(tomorrow)

2019-11-19
2019-11-20
2019-11-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [72]:
import numpy as np
a = np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [75]:
import numpy as np
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [79]:
import numpy as np
Z = np.random.uniform(0,10,10)
print (Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[5.0660691  6.03559513 4.44062699 6.33231735 7.29060589 5.01905445
 4.03155812 5.03882227 2.82449836 9.54613291]
[5. 6. 4. 6. 7. 5. 4. 5. 2. 9.]
[5. 6. 4. 6. 7. 5. 4. 5. 2. 9.]
[5. 6. 4. 6. 7. 5. 4. 5. 2. 9.]
[5 6 4 6 7 5 4 5 2 9]
[5. 6. 4. 6. 7. 5. 4. 5. 2. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [81]:
import numpy as np
a = zeros((5,5))
a += np.arange(5)
print(a)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [86]:
def generate():
    for x in range(10):
        yield x

import numpy as np
a = np.fromiter(generate(),dtype=float,count=-1)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [87]:
import numpy as np
a = np.linspace(0,1,11,endpoint=False)[1:]
print(a)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [88]:
import numpy as np
a = np.random.random(10)
print(a)
a.sort()
print(a)

[0.65530313 0.04224539 0.12700942 0.73647348 0.34808982 0.53236171
 0.54006925 0.65086387 0.2954743  0.27613329]
[0.04224539 0.12700942 0.27613329 0.2954743  0.34808982 0.53236171
 0.54006925 0.65086387 0.65530313 0.73647348]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [89]:
import numpy as np
a = np.random.random(10)
print(a)
sum = np.add.reduce(a)
print(sum)

[0.25439095 0.04030158 0.03183187 0.44608769 0.09070805 0.32337613
 0.98970713 0.52027476 0.99944316 0.13700062]
3.833121940373316


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [91]:
import numpy as np
a = np.random.randint(0,2,5)
b = np.random.randint(0,2,5)
print(a)
print(b)
check = np.allclose(a,b)
print(check)
ckeck = np.array_equal(a,b)
print(ckeck)

[0 0 0 1 1]
[0 0 0 1 0]
False
False


#### 43. Make an array immutable (read-only) (★★☆)

In [92]:
import numpy as np
Z = np.zeros(10)
print(Z)
Z.flags.writeable = False
Z[0] = 1
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [96]:
import numpy as np
a = np.random.random((10,2))
print(a)
x,y = a[:,0],a[:,1]
print('\n',x**2 + y**2,'\n')
print(arctan2(y,x))

[[0.62627638 0.25553925]
 [0.78937281 0.96975247]
 [0.18413689 0.35583941]
 [0.86734197 0.60304732]
 [0.51759529 0.92228868]
 [0.76216513 0.79334128]
 [0.89622116 0.37318758]
 [0.12154239 0.62215136]
 [0.44536579 0.01162769]
 [0.60367048 0.23149691]]

 [0.45752241 1.56352927 0.16052808 1.11594816 1.11852128 1.21028607
 0.94248134 0.40184487 0.19848589 0.41800887] 

[0.38740916 0.88758044 1.09326912 0.60755254 1.05938928 0.80543792
 0.39456492 1.37786796 0.02610224 0.36618634]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [100]:
import numpy as np
a = np.random.random(10)
print(a,'\n')
print(a.max(),'\n')
a[a.argmax()] = 0
print(a)

[0.48559883 0.4949516  0.05344722 0.38901805 0.23090532 0.39712818
 0.88164741 0.64272281 0.64910796 0.0233888 ] 

0.8816474121244923 

[0.48559883 0.4949516  0.05344722 0.38901805 0.23090532 0.39712818
 0.         0.64272281 0.64910796 0.0233888 ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [101]:
import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [102]:
import numpy as np
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [103]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
-1.7976931348623157e+308
1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆)

In [104]:
import numpy as np
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [106]:
import numpy as np
a = np.arange(100)
b = np.random.uniform(100)
print(a)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
15.658842248862285
16


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [107]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [108]:
import numpy as np
import scipy
import scipy.spatial

a = np.random.random((100,2))
print(a)
print(scipy.spatial.distance.cdist(a,a))

[[0.19432349 0.3314132 ]
 [0.70734443 0.6976044 ]
 [0.18608695 0.73795181]
 [0.99856944 0.87238043]
 [0.61278517 0.31536659]
 [0.26564342 0.23314063]
 [0.47859382 0.9779183 ]
 [0.02923649 0.70815077]
 [0.68623436 0.84148   ]
 [0.72236273 0.0161854 ]
 [0.61598134 0.69313324]
 [0.59417361 0.59692562]
 [0.12935834 0.107825  ]
 [0.92787769 0.1061006 ]
 [0.37805987 0.86709886]
 [0.4473093  0.73505013]
 [0.92508989 0.06150292]
 [0.25265222 0.26991302]
 [0.92411379 0.69657601]
 [0.1377906  0.49475337]
 [0.89536379 0.41834413]
 [0.3324044  0.35455407]
 [0.91426238 0.41733795]
 [0.49871597 0.73663744]
 [0.23611163 0.18971668]
 [0.78161362 0.54332432]
 [0.88599158 0.37150773]
 [0.29098528 0.63128215]
 [0.65472525 0.34617706]
 [0.39855966 0.85188309]
 [0.11727539 0.56050732]
 [0.69429647 0.17874394]
 [0.21594398 0.74650704]
 [0.08228193 0.96616318]
 [0.48400822 0.81834983]
 [0.08155558 0.61791207]
 [0.63668365 0.02471786]
 [0.14772525 0.79798862]
 [0.27128821 0.16489263]
 [0.56622649 0.6837538 ]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [110]:
import numpy as np
Z = np.arange(10, dtype=np.int32)
print(Z)
Z = Z.astype(np.float32, copy=False)
print(Z)

[0 1 2 3 4 5 6 7 8 9]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [111]:
from io import StringIO
import numpy as np
 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [112]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [113]:
import numpy as np
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [114]:
import numpy as np
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [115]:
import numpy as np
a = np.random.rand(5,10)
print(a)
b = a - a.mean(axis=1,keepdims=True)
print(b)

[[0.11321788 0.31238678 0.56996588 0.78017836 0.64661426 0.09170584
  0.34642759 0.92731661 0.59168826 0.59868473]
 [0.90367507 0.86925828 0.74098182 0.66202783 0.06366841 0.46806511
  0.32019201 0.34597923 0.99530221 0.04551236]
 [0.42504639 0.58762195 0.8844682  0.33200002 0.88805248 0.12901563
  0.41239613 0.37185483 0.46002788 0.23483907]
 [0.65838607 0.87494985 0.50705143 0.61993091 0.16904723 0.83180887
  0.10615145 0.17143446 0.72254422 0.69086891]
 [0.64129164 0.98450452 0.78034005 0.66644054 0.4406261  0.13770964
  0.7223273  0.73500126 0.97204454 0.4072146 ]]
[[-0.38460074 -0.18543184  0.07214726  0.28235974  0.14879564 -0.40611278
  -0.15139103  0.42949799  0.09386964  0.10086611]
 [ 0.36220883  0.32779205  0.19951558  0.1205616  -0.47779782 -0.07340112
  -0.22127422 -0.195487    0.45383597 -0.49595387]
 [-0.04748587  0.1150897   0.41193595 -0.14053224  0.41552022 -0.34351662
  -0.06013613 -0.10067742 -0.01250438 -0.23769319]
 [ 0.12316873  0.33973251 -0.02816591  0.08471357

#### 59. How to sort an array by the nth column? (★★☆)

In [116]:
import numpy as np
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 7 7]
 [7 7 6]
 [3 9 8]]
[[9 7 7]
 [7 7 6]
 [3 9 8]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [117]:
import numpy as np
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆)

In [118]:
import numpy as np
a = np.arange(100)
b = np.random.uniform(100)
print(a)
print(b)
index = (np.abs(a-b)).argmin()
print(a[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
61.65778226121074
62


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [119]:
import numpy as np
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [120]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [122]:
import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[3. 3. 2. 3. 2. 3. 4. 3. 3. 4.]
[5. 5. 3. 5. 3. 5. 7. 5. 5. 7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [123]:
import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [124]:
import numpy as np
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
n = len(np.unique(F))
print(n)

8


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [125]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[68 61 53 60]
 [66 52 53 56]
 [71 38 40 41]]
[[68 61 53 60]
 [66 52 53 56]
 [71 38 40 41]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [127]:
import numpy as np
import pandas as pd

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
print(pd.Series(D).groupby(S).mean())

0    0.412300
1    0.462907
2    0.423546
3    0.384139
4    0.501627
5    0.530969
6    0.474994
7    0.341786
8    0.570243
9    0.497988
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [128]:
import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
print(np.diag(np.dot(A,B)))

[0.88907324 1.1886227  2.2876167  1.33404615 0.96193736]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [129]:
import numpy as np
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [130]:
import numpy as np
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [131]:
import numpy as np
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [132]:
import numpy as np
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1, 69) ( 1, 88) ( 2, 19) ( 2, 79) ( 7, 26) ( 7, 66) ( 9, 21) ( 9, 86)
 (14, 89) (14, 98) (18, 36) (18, 77) (19, 79) (21, 86) (22, 23) (22, 26)
 (23, 26) (26, 66) (30, 45) (30, 62) (36, 51) (36, 77) (36, 79) (45, 62)
 (51, 79) (69, 88) (74, 76) (74, 82) (76, 82) (89, 98)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [133]:
import numpy as np
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [134]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)